---
apiVersion: v1
kind: Namespace
metadata:
  name: vega
  labels:
    vega.app: simon
    app.kubernetes.io/part-of: simon
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: vm
