apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
  namespace: "clickhouse"
spec:
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.11
  configuration:
    users:
      admin/password: admin
      admin/profile: default
      admin/quota: default
      admin/networks/ip:
        - 0.0.0.0/0
      readonly/password: readonly_password
      readonly/profile: readonly
      readonly/quota: default
      readonly/networks/ip:
        - 0.0.0.0/0
    profiles:
      readonly/readonly: 1
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
    clusters:
      - name: "default"
        templates:
          podTemplate: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
