# https://docs.gitlab.com/install/docker/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: vega
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:18.4.0-ce.0
        securityContext:
          readOnlyRootFilesystem: false
        env:
        - name: GITLAB_ROOT_PASSWORD
          value: "9a3bd550-f534-4356-8dcd-393df51c7cd1"
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://gitlab.vega.svc.cluster.local';
            prometheus_monitoring['enable'] = false
            sidekiq['metrics_enabled'] = false
            puma['exporter_enabled'] = false

        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/opt/gitlab
        - name: logs
          mountPath: /var/log/gitlab
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: data
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: vega
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    targetPort: 22
