{
 "title": "oteldb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" },
   {
    "name": "db",
    "query": "SELECT name FROM system.databases WHERE name NOT IN ('INFORMATION_SCHEMA', 'system', 'information_schema')"
   },
   {
    "name": "table",
    "label": "table",
    "query": "SELECT DISTINCT table FROM system.parts WHERE active = 1 AND database = '${db}' ORDER BY table;"
   },
   { "name": "logs", "query": "loki" },
   { "name": "metrics", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() FROM ${db}.traces_spans"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count() FROM ${db}.logs" }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() FROM ${db}.metrics_points"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (signal) (label_replace(delta({\"chstorage.inserts\"}[$__range]), \"signal\", \"$1\", \"chstorage.signal\", \"(.*)\"))",
     "legendFormat": "{{signal}}"
    }
   ]
  },
  { "title": "Rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "${table}",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 9 },
   "repeat": "table",
   "targets": [
    {
     "rawSql": "SELECT\n    column,\n    formatReadableSize(sum(column_data_compressed_bytes) AS size) AS compressed,\n    formatReadableSize(sum(column_data_uncompressed_bytes) AS usize) AS uncompressed,\n    round(usize / size, 2) AS ratio,\n    sum(rows) rows_cnt,\n    formatReadableSize(round(usize / rows_cnt, 2)) avg_row_size\nFROM system.parts_columns\nWHERE (active = 1) AND (database = '${db}') AND (table = '${table}')\nGROUP BY column\nORDER BY size DESC;"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "select parts.*,\n       columns.compressed_size,\n       columns.uncompressed_size,\n       columns.ratio\nfrom (\n         select table,\n                formatReadableSize(sum(data_uncompressed_bytes))          AS uncompressed_size,\n                formatReadableSize(sum(data_compressed_bytes))            AS compressed_size,\n                round(sum(data_uncompressed_bytes) / sum(data_compressed_bytes), 2) AS ratio\n         from system.columns\n         where database = '${db}'\n         group by table\n         ) columns\n         right join (\n    select table,\n           sum(rows)                                            as rows,\n           formatReadableSize(sum(bytes))                       as disk_size,\n           formatReadableSize(sum(primary_key_bytes_in_memory)) as primary_keys_size,\n           any(engine)                                          as engine,\n           sum(bytes)                                           as bytes_size\n    from system.parts\n    where active and database = '${db}'\n    group by database, table\n    ) parts on columns.table = parts.table\norder by parts.bytes_size desc;"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"go-faster.oteldb\", level!=\"DEBUG\"}"
    }
   ]
  }
 ]
}