# ClusterRole to list namespaces and pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vega
  namespace: vega
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list"]
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vega-sa
  namespace: vega
---
# ClusterRoleBinding to bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vega-binding
  namespace: vega
subjects:
  - kind: ServiceAccount
    name: vega-sa
    namespace: vega
roleRef:
  kind: ClusterRole
  name: vega
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: vega
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vega-api
  template:
    metadata:
      labels:
        app: vega-api
        vega.app: vega.api
        app.kubernetes.io/name: vega.api
        app.kubernetes.io/part-of: vega
    spec:
      serviceAccountName: vega-sa
      containers:
        - name: api
          image: vega
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 500m
              memory: 32Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: PYROSCOPE_APP_NAME
              value: "vega.api"
            - name: PYROSCOPE_ENABLE
              value: "true"
            - name: PYROSCOPE_URL
              value: "http://pyroscope.monitoring.svc.cluster.local:4040"
            - name: PROMAPI_URL
              value: "http://vmselect-cluster.vm.svc.cluster.local:8481/select/0/prometheus"
---
# service for simon-server
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vega
spec:
  selector:
    app: vega-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: "http"
