---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.100.1.0/24
  kubeProxyMode: none
  dnsSearch: []
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: InitConfiguration
        nodeRegistration:
          taints: []
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: "worker"
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 30001
        hostPort: 443
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 30002
        hostPort: 15021
        listenAddress: 127.0.0.1
        protocol: TCP
