// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetApplicationOperation  OperationName = "GetApplication"
	GetApplicationsOperation OperationName = "GetApplications"
	GetHealthOperation       OperationName = "GetHealth"
)
