// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetApplication implements getApplication operation.
//
// Get application.
//
// GET /applications/{name}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r *ApplicationSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplications implements getApplications operation.
//
// Get application list.
//
// GET /applications
func (UnimplementedHandler) GetApplications(ctx context.Context) (r ApplicationList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get health.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
