name: e2e

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: e2e-${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            e2e-${{ runner.os }}-${{ runner.arch }}-go-

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up helm
        uses: azure/setup-helm@v4.2.0

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.29.12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install cilium command line utility
        run: |
          curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/v0.16.22/cilium-linux-amd64.tar.gz{,.sha256sum}
          sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin

      - name: Add helm repositories
        run: |
          helm repo add cilium https://helm.cilium.io
          helm repo add clickhouse-operator https://docs.altinity.com/clickhouse-operator/
          helm repo add faster https://go-faster.github.io/charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add vm https://victoriametrics.github.io/helm-charts/
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo add minio-operator https://operator.min.io

          helm repo update

      - name: Install vega
        run: go run ./cmd/vega-install

      - name: Wait for vega
        run: kubectl -n vega rollout status --timeout=2m daemonset vega-agent
        env:
          KUBECONFIG: _out/kubeconfig.yml

      - name: Wait for grafana
        run: kubectl -n monitoring rollout status deployment grafana
        env:
          KUBECONFIG: _out/kubeconfig.yml

      - name: Wait for oteldb
        run: kubectl -n faster rollout status deployment otel-oteldb
        env:
          KUBECONFIG: _out/kubeconfig.yml

